# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

pool:
  vmImage: 'Ubuntu 16.04'
  #vmImage: 'vs2017-win2016'

variables:
  configuration: Debug, Release, MinSizeRel
  cmake_args: '-DPDC_WIDE=ON -DPDC_UTF8=OFF', '-DPDC_WIDE=OFF -DPDC_UTF8=ON'

steps:
- script: |
    cd $(agent.homeDirectory)
    mkdir build && cd build
    #-G"NMake Makefiles" 
    cmake -DCMAKE_VERBOSE_MAKEFILE=FALSE
          -DCMAKE_BUILD_TYPE=$(configuration)
          -DCMAKE_INSTALL_PREFIX=$(agent.homeDirectory)/build/dist $(cmake_args)
          ..
    cmake --build . --config $(configuration) --target install
  
  displayName: 'CMake $(configuration)'
